name: Dart

on:
  pull_request:

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603
      - uses: subosito/flutter-action@v2

      - name: Install dependencies
        run: flutter pub get

  analyze:
    steps:
      - name: Analyze project source
        run: dart analyze

  test:
    steps:
      - name: Run tests
        run: flutter test